"""Write packaging/deps.generated.iss: installer entries that download PyTorch and
torchaudio straight from the official PyTorch wheel index (download.pytorch.org),
verified with the SHA-256 the index publishes. Called by build.ps1.

The versions are whatever is installed in .venv, so the app and the downloaded wheels
always match. A .whl is a zip, which Inno Setup extracts into {app}\\_internal, where the
packaged app imports it from disk.

Prints the torch version on the last line (used as the "runtime" id in files.json: an
in-app partial update is only offered while it stays the same).
"""

import importlib.metadata as md
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
PY_TAG = f"cp{sys.version_info.major}{sys.version_info.minor}"


def wheel(pkg: str) -> dict:
    version = md.version(pkg)                     # e.g. 2.11.0+cu128
    local = version.split("+")[1]                 # cu128
    index = f"https://download.pytorch.org/whl/{local}/{pkg}/"
    ua = {"User-Agent": "Mozilla/5.0 LiveTranslate-build"}
    html = urllib.request.urlopen(urllib.request.Request(index, headers=ua), timeout=30).read().decode()
    name = f"{pkg}-{version.replace('+', '%2B')}-{PY_TAG}-{PY_TAG}-win_amd64.whl"
    m = re.search(r'href="([^"#]*' + re.escape(name) + r')#sha256=([0-9a-f]{64})"', html)
    if not m:
        raise SystemExit(f"{name} not found on {index}")
    url, sha = m.group(1), m.group(2)
    req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "Mozilla/5.0 LiveTranslate-build"})
    size = int(urllib.request.urlopen(req, timeout=30).headers["Content-Length"])
    dist_info = f"{pkg}-{version}.dist-info"
    return {"pkg": pkg, "version": version, "url": url, "sha256": sha, "size": size,
            "marker": dist_info + "\\RECORD"}


def main() -> None:
    wheels = [wheel("torch"), wheel("torchaudio")]
    lines = ["; Generated by make_deps.py from the official PyTorch wheel index. Do not edit."]
    for w in wheels:
        check = f"NeedWheel('{w['marker']}')"
        lines.append(
            f'Source: "{w["url"]}"; DestName: "{w["pkg"]}-{w["version"].replace("+", "-")}.zip"; '
            f'DestDir: "{{app}}\\_internal"; Hash: "{w["sha256"]}"; ExternalSize: {w["size"]}; '
            f"Flags: external download extractarchive recursesubdirs createallsubdirs ignoreversion; "
            f'Check: {check}')
        print(f"{w['pkg']} {w['version']}: {w['size'] / 1e9:.2f} GB from {w['url']}")
    (HERE / "deps.generated.iss").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(wheels[0]["version"])


if __name__ == "__main__":
    main()
